### ISSUE TITLE
Create beautiful, pretty UI design

### ISSUE THREAD

**Issue by martinszeltins** [openrecall/openrecall#18]
Just like the Microsoft Recall which has modern UI, please create a beautiful enjoyable UI

Something like this:
![image](https://github.com/openrecall/openrecall/assets/34019878/cebadc1c-4c94-43be-9618-52aadf96e55c)

**Comment by scarlettekk** [comment]
Pull requests are always welcome!

**Comment by martinszeltins** [comment]
1. Can someone explain why this issue got 5 thumbs down? 👎🏻 Do people not like nice UIs?
2. Can this be implemented as a frontend that is seperate from the backend? For example using a [Nuxt](https://nuxt.com/) framework that communicates with the openrecall backend? I assume this would require changes on the backend, right?

cc. @koenvaneijk Would like to hear your thoughts on #2

**Comment by scarlettekk** [comment]
People thumbs it down because it is a very large, vague ask to replace something that already exists with something you feel is better - there's nothing wrong with that, but it's important to remember that everyone working on this project is volunteering their time and they may prefer to focus on core parts of the program before doing something like beautifying the UI.

**Comment by koenvaneijk** [comment]
Fully agree, the UI could use some work.

For the next version we're working on a couple of different items which have been prioritized due to requested functionality, but eventually we will have to improve the UI.

For now I will close this issue as it is not related to a specific feature or a bug, I have however opened a discussion here:
https://github.com/openrecall/openrecall/discussions/35

Thank you @martinszeltins for your input, hope to continue the discussion at the above link.
